[workspace]
resolver = "3"
members = [
    "lambdas/http",
    "lambdas/presigned-cleanup",
    "lambdas/upload-completion",
]

[workspace.dependencies]
dotenvy = "=0.15.7"

# Docbox HTTP layer
docbox-http = "0.7.1"

# Docbox Core
docbox-core = "0.11.0"

# Bytes type used for cheap shared bytes (and utilities)
bytes = "=1.11.0"
bytes-utils = "=0.1.4"

# Logging
tracing = "=0.1.44"

# Error handling
thiserror = "=2.0.18"

# Date & time
chrono = { version = "=0.4.43", features = ["serde"] }

# AWS configuration
aws-config = { version = "=1.8.12", features = ["behavior-version-latest"] }

# Serialization and JSON
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"

# [patch.crates-io]
# docbox-http = { version = "0.7.0", path = "../docbox/packages/docbox-http" }
# docbox-core = { version = "0.10.0", path = "../docbox/packages/docbox-core" }
