[package]
name = "docbox-http-lambda"
version = "0.0.4"
edition = "2024"

[dependencies]
dotenvy.workspace = true

lambda_http = "1.0.0"

tokio = { version = "1", features = ["macros"] }

# HTTP server framework
axum = { version = "=0.8.8" }

# HTTP layers for ratelimiting, CORS, and tracing
tower-http = { version = "=0.6.8", features = ["limit", "cors", "trace"] }

docbox-http.workspace = true
docbox-core.workspace = true

serde.workspace = true
serde_json.workspace = true

thiserror.workspace = true
