[package]
name = "docbox-management-lambda"
version = "0.0.3"
edition = "2024"

[dependencies]
dotenvy.workspace = true

tokio = { version = "1", features = ["macros"] }

docbox-management.workspace = true
docbox-management-interface.workspace = true

serde.workspace = true
serde_json.workspace = true

thiserror.workspace = true

tracing.workspace=  true

lambda_runtime = { version = "1.3.0", features = ["tracing"] }
